# key: val (needed this because we cant keep this file empty)

AUGMENTATION: True
IMAGE_SIZE: [299, 299, 3] # as per Xception model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 4  # [Cyst, Normal, Stone, Tumor]
WEIGHTS: imagenet
LEARNING_RATE: 0.01